"""empty message

Revision ID: d263d52fb47f
Revises: 
Create Date: 2022-03-19 19:53:22.527367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd263d52fb47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rooms', sa.String(length=4), nullable=True),
    sa.Column('bathrooms', sa.String(length=4), nullable=True),
    sa.Column('price', sa.String(length=15), nullable=True),
    sa.Column('ptype', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photourl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
